name: vaDAI with RariFuse Leverage Strategy
on:
  pull_request:
    paths:
      - "test/vadai/rarifuse-leverage.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundLeverageStrategy.sol"
      - "contracts/strategies/rari-fuse/RariFuseLeverageStrategy.sol"
      
jobs:
  vadai-rarifuse-leverage-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vaDAI RariFuse Leverage
        run: npm test "test/vadai/rarifuse-leverage.js"
