name: vaWBTC with Convex 4Metapool ibBTC
on:
  pull_request:
    paths:
      - "test/vwbtc/crv-cvx-4metapool-ibbtc.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/convex/ConvexStrategyBase.sol"
      - "contracts/strategies/convex/4Pool/Convex4PoolStrategy.sol"
      - "contracts/strategies/convex/4Pool/Convex4MetaPoolStrategy.sol"
      - "contracts/strategies/convex/4Pool/Convex4MetaPoolStrategyIBBTCPool.sol"

jobs:
  vawbtc-convex4mp-ibbtc-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vaWBTC with Convex 4Metapool ibBTC
        run: npm test "test/vwbtc/crv-cvx-4metapool-ibbtc.js"
