name: vDAI with Convex 4Pool
on:
  pull_request:
    paths:
      - "test/vdai/crv-cvx-4pool-susd.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/convex/ConvexStrategyBase.sol"
      - "contracts/strategies/convex/4Pool/Convex4PoolStrategy.sol"
      - "contracts/strategies/convex/4Pool/Convex4PoolStrategySUSDPool.sol"

jobs:
  vdai-convex4p-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vDAI with Curve 4Pool
        run: npm test "test/vdai/crv-cvx-4pool-susd.js"
