name: vDAI pool with Curve Strategy
on: [pull_request]

jobs:
  vdai-curve-strategy-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for Curve Strategy Manager
        run: npm test "test/curve/crv-3pool-mgr.js"

      - name: Running tests for vDAI pool with Curve Strategy
        run: npm test "test/curve/vdai-crv-3pool.js"

      - name: Running tests for vUSDC pool with Curve Strategy
        run: npm test "test/curve/vusdc-crv-3pool.js"
