name: vDAI with Alpha Lend
on:
  pull_request:
    paths:
      - "test/utils/setupHelper.js"
      - "test/vdai/alpha-lend.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategyDAI.sol"

jobs:
  vdai-alphalend-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vDAI with Alpha Lend
        run: npm test "test/vdai/alpha-lend.js"
