name: vDAI with Curve 4Pool Metapool
on:
  pull_request:
    paths:
      - "test/vdai/crv-4pool-mim.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/curve/CrvPoolStrategyBase.sol"
      - "contracts/strategies/curve/4Pool/Crv4PoolStrategy.sol"
      - "contracts/strategies/curve/4Pool/Crv4MetaPoolStrategy.sol"
      - "contracts/strategies/curve/4Pool/Crv4MetaPoolStrategyMIMPool.sol"

jobs:
  vdai-curve4mp-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vDAI with Curve 4Pool Metapool
        run: npm test "test/vdai/crv-4pool-mim.js"
