name: Vesper Pool test
on: [pull_request]

jobs:
  vesper-pool-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for Vesper Pool
        run: npm test "test/behavior/vesper-pool.js"

      - name: Running tests for Vesper Multi Pool
          run: npm test "test/behavior/vesper-multi-pool.js"

      - name: Running tests for Vesper Pool Admin
          run: npm test "test/vesper-pool-admin.js"
