name: veETH-DAI with Aave
on:
  pull_request:
    paths:
      - "test/veth/earn-aave.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/aave/AaveStrategy.sol"
      - "contracts/strategies/aave/earn/EarnAaveStrategy.sol"
      - "contracts/strategies/aave/earn/EarnAaveStrategyETH.sol"

jobs:
  veth-earn-aave:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running veETH-DAI with Aave
        run: npm test "test/veth/earn-aave.js"
