name: veETH-DAI with Vesper
on:
  pull_request:
    paths:
      - "test/utils/setupHelper.js"
      - "test/veth/vesper-earn-maker.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/maker/EarnVesperMakerStrategy.sol"
      - "contracts/strategies/maker/VesperMakerStrategy.sol"
      - "contracts/strategies/maker/earn/EarnVesperMakerStrategyETH.sol"

jobs:
  veth-earn-vesper:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH-DAI with Vesper
        run: npm test "test/veth/vesper-earn-maker.js"
