name: vFRAX with Convex D3 Pool
on:
  pull_request:
    paths:
      - "test/vafrax/crv-cvx-4pool.js"
      - "test/vafrax/crv-cvx-d3pool.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/convex/ConvexStrategyBase.sol"
      - "contracts/strategies/convex/3pool/ConvexD3PoolStrategy.sol"
      - ".github/workflows/vfrax-convex-d3pool.yml"

jobs:
  vfrax-convex4mp-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vFRAX with with Convex D3 Pool
        run: npm test "test/vafrax/crv-cvx-d3pool.js"
