name: vMIM with Convex 4Pool Metapool
on:
  pull_request:
    paths:
      - "test/vmim/crv-cvx-4pool.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/convex/ConvexStrategyBase.sol"
      - "contracts/strategies/curve/4Pool/Convex4PoolStrategy.sol"
      - "contracts/strategies/curve/4Pool/Convex4MetaPoolStrategy.sol"
      - "contracts/strategies/curve/4Pool/Convex4MetaPoolStrategyMIMPool.sol"

jobs:
  vmim-convex4mp-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vMIM with Convex 4Pool Metapool
        run: npm test "test/vmim/crv-cvx-4pool.js"
