name: vUSDC with Rari Fuse
on: [pull_request]

jobs:
  vusdc-rarifuse-strategy-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vUSDC with Rari Fuse
        run: npm test "test/vusdc/rari-fuse.js"