name: veWBTC-DAI with Vesper Maker
on:
  pull_request:
    paths:
      - "test/utils/setupHelper.js"
      - "test/vwbtc/vesper-earn-maker.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/maker/MakerStrategy.sol"
      - "contracts/strategies/maker/earn/EarnVesperMakerStrategy.sol"
      - "contracts/strategies/maker/earn/EarnVesperMakerStrategyWBTC.sol"

jobs:
  vwbtc-earn-vesper-maker:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vWBTC-DAI with Vesper Maker
        run: npm test "test/vwbtc/vesper-earn-maker.js"
