name: vWBTC with Vesper Compound XY
on:
  pull_request:
    paths:
      - "test/vwbtc/vesper-compound-xy.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundXYStrategy.sol"
      - "contracts/strategies/compound/VesperCompoundXYStrategy.sol"

jobs:
  vwbtc-vesper-compound-xy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vWBTC with Vesper Compound XY
        run: npm test "test/vwbtc/vesper-compound-xy.js"
